site_name: REDCap.jl
repo_url: https://github.com/bcbi/REDCap.jl.git
site_description: Documentation for REDCap.jl
site_author: FLCN17
docs_dir: 'build/'
pages:
  - Home: index.md
  - Export: export.md
  - Import: import.md
  - Deletion: delete.md
  - Utilities: utils.md
theme: readthedocs
